### ISSUE TITLE
部分链接无反应，另外貌似存在限流

### ISSUE THREAD

**Issue by imldy** [simonsmh/telegram-bili-feed-helper#22]
测试链接1（无反应）：https://www.bilibili.com/video/BV1dH4y1f7LN/

测试链接2（有反应）：https://www.bilibili.com/video/BV1Pm4y1G78s/

多次测试后发现Bot对两个链接都不作回复了，看起来像是存在频率限制。

**Comment by simonsmh** [comment]
感觉还是koyeb的容器内存太小，发这个视频有点困难，我再观察下

**Comment by simonsmh** [comment]
为文件下载上传部分添加了一个文件名与tg文件id的关系映射表，现在相同的文件（图片、视频、音频等）不会再重复下载并向tg发送文件，减少了bot压力。另之前用db缓存b站api请求，现在换成redis比db快很多

**Comment by imldy** [comment]
哇，感谢！
