### ISSUE TITLE
重复处理的可能

### ISSUE THREAD

**Issue by sudoskys** [simonsmh/telegram-bili-feed-helper#39]
https://github.com/simonsmh/telegram-bili-feed-helper/blob/ba087ec29c82c6abb77bc08bfd1ba43e34389ac0/biliparser/__main__.py#L676-L685

两个群组若都引进了此机器人，用户从一个群组引用转发到另一群组可能导致重复处理

**Comment by simonsmh** [comment]
https://github.com/simonsmh/telegram-bili-feed-helper/blob/master/biliparser/__main__.py#L148-L169

**Comment by sudoskys** [comment]
![图片](https://github.com/user-attachments/assets/43fa25ae-67ed-45a5-b3ba-c3c275881ea4)

**Comment by simonsmh** [comment]
只能避免自己处理自己发的消息，你举例图2的这种真没办法
